### ISSUE TITLE
Allow passing existing JedisPool to driver

### ISSUE THREAD

**Issue by JoonasC** [FalkorDB/JFalkorDB#23]
I noticed that JFalkorDB uses Jedis under the hood. Would it be possible to pass an existing JedisPool instance to the driver upon initialization, instead of it creating its own instance each time?

**Comment by gkorland** [comment]
We prefer not to expose it, since we plan to upgrade to Jedis 5.0 in the near future and Jedis 5.0 is using different Pool API.
Can you please extend on your use case? Are you creating many JFalkorDB connections?

**Comment by JoonasC** [comment]
I am running JFalkorDB in parallel with Jedi's, so I thought I could reuse my JedisPool instance.

**Comment by gkorland** [comment]
which version of Jedis are you using?

**Comment by JoonasC** [comment]
I downgraded to the same version as used in JFalkorDB (3.10.0), since doing that didn't cause any compatibility issues with my existing code.

**Comment by gkorland** [comment]
You can try this "internal" constructor. 
https://github.com/FalkorDB/JFalkorDB/blob/f56ed496329f64691a8ecc1cd6859118de0386fd/src/main/java/com/falkordb/impl/api/DriverImpl.java#L54
