### ISSUE TITLE
Graph copy

### ISSUE THREAD

**Issue by JoonasC** [FalkorDB/JFalkorDB#25]
I noticed that graph copy was recently implemented in FalkorDB but it is missing here.

**Comment by gkorland** [comment]
yes, we'll add it soon, PRs are more than welcome :1st_place_medal:

**Comment by JoonasC** [comment]
@gkorland I have submitted a PR, I would appreciate if it could be merged/reviewed soon

**Comment by JoonasC** [comment]
@gkorland Thanks for merging my PR, I would still need a new version release for maven

**Comment by JoonasC** [comment]
@gkorland ?

**Comment by gkorland** [comment]
Sure I'll release it later tonight

**Comment by gkorland** [comment]
Done. Check v0.3.0
